# _CONF/deploy/backend_deploy_dir/nginx/default.conf
#user www-data;
worker_processes auto;
#pid /run/nginx.pid;
pid /tmp/nginx.pid;
#error_log /var/log/nginx/error.log;
error_log /tmp/error.log;
#include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 768;
	# multi_accept on;
}

http {
    # Rediriger TOUS les répertoires temporaires
    client_body_temp_path /tmp/client_body_temp;
    proxy_temp_path /tmp/proxy_temp;
    fastcgi_temp_path /tmp/fastcgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;
    scgi_temp_path /tmp/scgi_temp;
    
    # Logs accessibles
    access_log /tmp/access.log;

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	types_hash_max_size 2048;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	gzip on;

    server {
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;


        listen ${PORT_REV_PROXY_BACKEND_EXTERNAL};

        location / {
            # Configuration index.html
            root /etc/nginx/html;
            index index.html;
            try_files $uri $uri/ =404;
        }


        location /api-backend/ {
            #proxy_pass http://api-backend:8001/;
            proxy_pass http://127.0.0.1:${PORT_FASTAPI_BACKEND_EXTERNAL}/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # Activate Swagger /docs/
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /mlflow/ {
            # Authentifie via FastAPI
            auth_request /api-backend/verify-backend-access;
            
            # En cas d'échec d'auth, afficher l'erreur fournie par l'API
            auth_request_set $auth_status $upstream_status;
            error_page 401 = /api-backend/login;

            # PROXY pour domaine externe HTTPS
            # THIS URL SHOULD BE THE DEPLOYED MLFLOW SERVER ON HF SPACES - NOT THE LOCAL SERVER FOR DEV ANYMORE
            proxy_pass ${MLFLOW_PROXY_PASS}/;  # ← Ajout du / final

            # Headers corrigés pour domaine externe
            proxy_set_header Host huggingface.co;  # ← HOST CIBLE, pas $host
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;  # ← HTTPS, pas $scheme
            
            # Configuration SSL pour proxy HTTPS
            proxy_ssl_verify off;
            proxy_ssl_server_name on;
            
            # Cookies
            proxy_set_header Cookie $http_cookie;
        }
    }
}


